function Void(){}function $id(a){if(typeof $=="function"){if(typeof a=="string"){if(a.indexOf("#")==0){return $(a);}else{return $("#"+a);}}return $(a);
}else{throw ("This function can only be used with jquery !");}}function isUndef(a){return typeof a=="undefined";}function isNull(a){return typeof a!="undefined"&&a==null;
}function eqNull(a){return a==null;}function asStr(a){return""+a;}function isInstanceOf(a,b){return a!=null&&a.constructor==b;}function isString(a){return a!=null&&(typeof a=="string"||a instanceof String);
}function isNumber(a){return a!=null&&(typeof a=="number"||a instanceof Number);}function isNum(a){return isNumber(a)&&!isNaN(a)&&isFinite(a);}function isBoolean(a){return a!=null&&(typeof a=="boolean"||a instanceof Boolean);
}function isFunction(a){return a!=null&&(typeof a=="function"||a instanceof Function);}function isPrimitive(a){return a!=null&&(isString(a)||isNumber(a)||isBoolean(a));
}function isDate(a){return a!=null&&a instanceof Date;}function isArray(a){return a!=null&&Object.prototype.toString.apply(a)=="[object Array]";}function isRegExp(a){return a!=null&&a instanceof RegExp;
}function isPlainObject(d,c){if(!d||Object.prototype.toString.call(d)!=="[object Object]"||d.nodeType||d.setInterval){return false;}var b=Object.prototype.hasOwnProperty;
if(d.constructor&&!b.call(d,"constructor")&&!b.call(d.constructor.prototype,"isPrototypeOf")){return false;}if(c==true){return true;}else{var a;for(a in d){}return a===undefined||b.call(d,a);
}}function isEmptyObject(b){for(var a in b){return false;}return true;}var ___STRING_LTRIM_REG=/^(\s)+/i;var ___STRING_RTRIM_REG=/(\s)+$/i;function lTrim(a){return a.replace(___STRING_LTRIM_REG,"");
}function rTrim(a){return a.replace(___STRING_RTRIM_REG,"");}function trim(a){return a.replace(___STRING_LTRIM_REG,"").replace(___STRING_RTRIM_REG,"");
}function strEql(b,a){if(b==null){return a==null;}else{if(a==null){return b==null;}else{return asStr(b)===asStr(a);}}}function strEqlAny(d){var c=arguments.length-1;
if(c<=0){return false;}if(isArray(arguments[1])){var a=arguments[1];c=a.length;for(var b=0;b<c;b++){if(strEql(d,a[b])){return true;}}}else{c++;for(var b=1;
b<c;b++){if(strEql(d,arguments[b])){return true;}}}return false;}String.prototype.lTrim=function(){return lTrim(this);};String.prototype.rTrim=function(){return rTrim(this);
};String.prototype.trim=function(){return trim(this);};String.prototype.isEmpty=function(){return this=="";};String.prototype.isBlank=function(){return trim(this)=="";
};function isNullOrEmpty(a){return a==null||asStr(a).isEmpty();}function isNullOrBlank(a){return a==null||asStr(a).isBlank();}var isNoE=isNullOrEmpty;var isNoB=isNullOrBlank;
function replaceStr(b,d,c){if(c==null){c="";}var a=b.split(d);return a.join(c);}function replaceRegStr(a,c,d){var b=new RegExp(c,"g");return a.replace(b,d);
}function left(c,b){if(!isString(c)){return null;}var a=c.length;if(b>=a){return c;}else{return c.substring(0,b);}}function right(c,b){if(!isString(c)){return null;
}var a=c.length;if(b>=a){return c;}else{return c.substring(a-b);}}function _padString(g,b,e,c){var d=""+g;var f=b-d.length;if(f<=0){return d;}if(c==null){c=" ";
}if(c.length<=0){throw"padStr 's length must be great than 0 !";}var a="";do{a+=c;if(a.length>=f){a=left(a,f);break;}}while(true);return e==true?d+a:a+d;
}function padLeft(c,a,b){return _padString(c,a,false,b);}function padRight(c,a,b){return _padString(c,a,true,b);}String.prototype.left=function(a){return left(this,a);
};String.prototype.right=function(a){return right(this,a);};function dupStr(d,c){if(!isNum(c)){return null;}c=Math.floor(c);var b="";if(c<=0){return b;
}b=d;for(var a=1;a<c;a++){b+=d;}return b;}function strStartsWith(b,a){if(!isString(a)){return false;}return(b.indexOf(a)===0);}function strEndsWith(b,a){if(!isString(a)){return false;
}var c=b.lastIndexOf(a);return(c!=-1)&&(c==b.length-a.length);}function strContains(c,b,d){if(!isString(b)){return false;}d===true;var a=d?c.toUpperCase().indexOf(b.toUpperCase()):c.indexOf(b);
return(a!=-1);}String.prototype.startsWith=function(a){return strStartsWith(this,a);};String.prototype.endsWith=function(a){return strEndsWith(this,a);
};String.prototype.contains=function(a,b){return strContains(this,a,b);};function formatStr(template){if(!isString(template)){return template;}var params=Array.prototype.slice.call(arguments,1);
var paramCount=params.length;if(paramCount==0){return template;}var nullAs=template.nullAs||"null";var resultStr="";var asObject=isPlainObject(params[0]);
if(asObject){params=params[0];var xReg=/\{[a-zA-Z_]+(\.[a-zA-Z_]+|\[\d+\])*\}?/mg;resultStr=template.replace(xReg,function(m){var holder=m.substring(1,m.length-1).trim();
var param=eval("params."+holder);return""+(param==null?nullAs:param);});}else{var xReg=/\{\d+}?/mg;resultStr=template.replace(xReg,function(m){var holder=m.substring(1,m.length-1).trim();
var index=parseInt(holder);if(index>=0&&index<paramCount){var param=params[index];return""+(param==null?nullAs:param);}else{return m;}});}return resultStr;
}String.prototype.format=function(){var a=[this].concat(Array.prototype.slice.call(arguments,0));return formatStr.apply(window,a);};String.prototype.isIn=function(){var a=[this].concat(Array.prototype.slice.call(arguments,0));
return strEqlAny.apply(window,a);};var __escapeStrReg={backslash:/\\/ig,quote:/'/ig,dblquote:/"/ig,newline:/\n/ig,carriage:/\r/ig,carriage2:/\r\n/ig,formfeed:/\f/ig,hrtab:/\t/ig,foreslash:/\//ig};
function escapeJsonStr(b,a){if(b==null||b==""){return b;}else{a=a===true;__escapeStrReg.backslash.lastIndex=-1;b=b.replace(__escapeStrReg.backslash,"\\\\");
if(a){__escapeStrReg.quote.lastIndex=-1;b=b.replace(__escapeStrReg.quote,"\\'");}else{__escapeStrReg.dblquote.lastIndex=-1;b=b.replace(__escapeStrReg.dblquote,'\\"');
}__escapeStrReg.newline.lastIndex=-1;b=b.replace(__escapeStrReg.newline,"\\n");__escapeStrReg.carriage.lastIndex=-1;b=b.replace(__escapeStrReg.carriage,"\\r");
__escapeStrReg.carriage2.lastIndex=-1;b=b.replace(__escapeStrReg.carriage2,"\\r\\n");__escapeStrReg.formfeed.lastIndex=-1;b=b.replace(__escapeStrReg.formfeed,"\\f");
__escapeStrReg.hrtab.lastIndex=-1;b=b.replace(__escapeStrReg.hrtab,"\\t");return b;}}String.prototype.escapeJson=function(a){return escapeJsonStr(this,a);
};String.builder=function(){var a=new String.builder.fn();a.append.apply(a,arguments);return a;};String.builder.fn=function(){this.value="";this.append=function(){for(var a=0,b=arguments.length;
a<b;a++){this.value=this.value+arguments[a];}};this.appendln=function(){this.append.apply(this,arguments);this.append("\n");};this.prepend=function(){for(var a=0,b=arguments.length;
a<b;a++){this.value=arguments[a]+this.value;}};this.clear=function(){this.value="";};this.toString=function(){return this.value;};};function parseDimen(d){if(d==null){return null;
}var b={};if(isNum(d)){b.value=d;b.unit="px";}else{if(isString(d)){var a=ParseFloat(d);if(isNum(a)){b.value=a;var c=asStr(b.value);var e=d.substring(c.length).trim();
b.unit=e==""?"px":e;}}}return b;}Number.prototype.round=function(g){if(!isNum(g)||g<0){g=0;}if(g==0){return Math.round(this);}var f=this+"";var d=f.indexOf(".");
if(d!=-1){var b=f.substring(0,d);var a=d==f.length-1?"":f.substring(d+1);if(a.length>g){var e=new Number(a.charAt(g));a=a.substring(0,g);if(e>=5){var c=new Number(a.charAt(g-1));
a=a.substring(0,g-1)+(c+1);}}f=a==""?b:b+"."+a;return new Number(f);}else{return this;}};Array.prototype.clear=function(){this.length=0;};Array.prototype.add=function(a){this[this.length]=a;
};function ParseInt(a){if(isString(a)){if(a.isBlank()){return NaN;}}return parseInt(a);}function ParseFloat(a){if(isString(a)){if(a.isBlank()){return NaN;
}}return parseFloat(a);}var __arrayMethodsToCheck=["slice","splice","shift","unshift"];Array.prototype.append=function(){for(var c=0,b=this.length,a=arguments.length;
c<a;c++,b++){this[b]=arguments[c];}};Array.prototype.prepend=function(){for(var b=0,a=arguments.length;b<a;b++){this.splice(0,0,arguments[b]);}};Array.prototype.clone=function(){return this.concat();
};Array.prototype.contains=function(b,a){return this.indexOf(b,null,a)>-1;};Array.prototype.every=function(e,d){d=d||window;var b=true;for(var c=0,a=this.length;
c<a&&b;c++){b=b&&e.call(d,this[c],c,this);}return b;};Array.prototype.filter=function(d,c){c=c||window;var e=new Array();for(var b=0,a=this.length;b<a;
b++){if(d.call(c,this[b],b,this)){e.push(this[b]);}}return e;};Array.prototype.reject=function(d,c){c=c||window;var e=new Array();for(var b=0,a=this.length;
b<a;b++){if(!d.call(c,this[b],b,this)){e.push(this[b]);}}return e;};Array.prototype.where=function(f){var d=f;var a=[];var e=a.length;if(d!=null){for(var b in d){a[e++]=b;
}e=a.length;}var c=function(j){if(j==d){return true;}else{if(d!=null&&j!=null){for(var h=0;h<e;h++){var g=a[h];if(d[g]!=j[g]){return false;}}return true;
}else{return false;}}};return this.filter(c);};Array.prototype.forEach=function(d,c){c=c||window;for(var b=0,a=this.length;b<a;b++){d.call(c,this[b],b,this);
}};Array.prototype.indexOf=function(e,b,d){if(b==null){b=0;}if(typeof d=="function"){for(var c=b,a=this.length;c<a;c++){if(d(this[c],e,c)){return c;}}}else{for(var c=b,a=this.length;
c<a;c++){if(this[c]==e){return c;}}}return -1;};Array.prototype.find=function(d){if(typeof d=="function"){for(var b=0,a=this.length;b<a;b++){var c=this[b];
if(d(c,b)){return c;}}}return null;};Array.prototype.insertAt=function(b,a){this.splice(a,0,b);return b;};Array.prototype.insertBefore=function(b,a){return this.insertAt(b,this.indexOf(a));
};Array.prototype.lastIndexOf=function(d,a,c){if(a==null||a>=this.length){a=this.length-1;}if(typeof(c)=="function"){for(var b=a;b>=0;b--){if(c(this[b],d,b)){return b;
}}}else{for(var b=a;b>=0;b--){if(this[b]==d){return b;}}}return -1;};Array.prototype.map=function(d,c){c=c||window;var e=new Array();for(var b=0,a=this.length;
b<a;b++){e.push(d.call(c,this[b],b,this));}return e;};Array.prototype.pluck=function(a){var b=function(c){return c==null?undefined:c[a];};return this.map(b);
};Array.prototype.remove=function(b,a){return this.removeAt(this.indexOf(b,null,a));};Array.prototype.removeAt=function(a){var b=undefined;if(a>=0&&a<this.length){b=this[a];
this.splice(a,1);}return b;};Array.prototype.some=function(e,c,d){if(typeof c=="number"){d=c||1;c=window;}else{d=d||1;c=c||window;}var f=0;for(var b=0,a=this.length;
b<a;b++){if(e.call(c,this[b],b,this)){f++;if(f>=d){return true;}}}return false;};Array.prototype.any=function(b,a){return this.some(b,a,1);};Array.prototype._slice=function(a,c){c=c||this.length;
var d=new Array();for(var b=a;b<c;b++){d.push(this[b]);}return d;};Array.prototype._shift=function(){var a=undefined;if(this.length>0){a=this[0];this.splice(0,1);
}return a;};Array.prototype._splice=function(e,d){var f=new Array();var b=new Array();for(var c=0;c<e;c++){f.push(this[c]);}for(var c=e;c<e+d;c++){b.push(this[c]);
}if(arguments.length>2){for(var c=2;c<arguments.length;c++){f.push(arguments[c]);}}for(var c=e+d,a=this.length;c<a;c++){f.push(this[c]);}for(var c=0,a=f.length;
c<a;c++){this[c]=f[c];}this.length=f.length;return b;};Array.prototype.sum=function(f,e){e=e||window;var c=null;if(typeof f!="function"){f=function(g){return g;
};}else{c=f();}var b=c;var a=this.length;if(a>0){b=f.call(e,this[0],0,this);for(var d=1;d<a;d++){b+=f.call(e,this[d],d,this);}}return b;};Array.prototype._unshift=function(){var aArgs=new Array();
for(var i=0,len=arguments.length;i<len;i++){aArgs.push("arguments["+i+"]");}eval("this.splice(0,0,"+aArgs.join(",")+")");};for(var i=0,len=__arrayMethodsToCheck.length;
i<len;i++){var method=__arrayMethodsToCheck[i];if(Array.prototype[method]==null){Array.prototype[method]=Array.prototype["_"+method];}}function sortArray(){var k=arguments;
var a=k[0];if(!isArray(a)){return a;}a=a.clone();var d=false;var l=null;if(k.length>1){if(typeof k[1]=="boolean"){d=k[1]==true;if(k.length>2&&typeof k[2]=="function"){l=k[2];
}}else{if(typeof k[1]=="function"){l=k[1];}}}if(l==null){l=function(n,j){return n-j;};}var h=a.length;for(var e=0;e<h-1;e++){var f=a[e];var g=e;for(var c=e+1;
c<h;c++){var b=a[c];var m=l(b,f);m=d?m>0:m<0;if(m){f=b;g=c;}}if(g>e){b=a[e];a[e]=f;a[g]=b;}}return a;}Array.prototype.sort=function(){var a=[this].concat(Array.prototype.slice.call(arguments,0));
return sortArray.apply(window,a);};Array.from=function(){return Array.prototype.concat.apply([],arguments);};function copyArray(d){var b=[];var a=d.length;
for(var c=0;c<a;c++){b[c]=d[c];}return b;}function declare(namespace){if(typeof namespace!="string"){return null;}namespace=namespace.trim();if(namespace==""){return null;
}var names=namespace.split(".");var ns=[];var nsName="";for(var i=0;i<names.length;i++){ns[i]=names[i];nsName=ns.join(".");if(eval("(typeof "+nsName+' == "undefined")')){if(i==0){eval("var "+nsName+" = window."+nsName+" = {};");
}else{eval(nsName+" = {};");}}}return eval(nsName);}function makeProxy(e,d){if(typeof d==="string"){var c=e[d];d=e;e=c;}if(d==null){d=window;}if(!isFunction(e)){return undefined;
}var a=Array.prototype.slice.call(arguments,2);var b=function(){return e.apply(d,a);};return b;}function isLeapYear(a){var b=null;if(isDate(a)){a=a.getFullYear();
}else{b=ParseInt(a);}if(!isNum(b)){return false;}return(0==b%4&&((b%100!=0)||(b%400==0)));}var __monthDaysNorm=[31,28,31,30,31,30,31,31,30,31,30,31];var __monthDaysLeap=[31,29,31,30,31,30,31,31,30,31,30,31];
var __weekDayChsNames=["日","一","二","三","四","五","六"];function getYearMonthDays(b,d){var a=isLeapYear(b);var e=ParseInt(d);var c=a?__monthDaysLeap:__monthDaysNorm;
return c[e-1];}Date.prototype.format=function(b){if(b==null){b="yyyy-MM-dd";}var a=b.replace(/yyyy/,this.getFullYear());a=a.replace(/yy/,padLeft(this.getYear(),2,"0"));
a=a.replace(/MM/,padLeft(this.getMonth()+1,2,"0"));a=a.replace(/M/,this.getMonth()+1);a=a.replace(/dd/,padLeft(this.getDate(),2,"0"));a=a.replace(/d/,this.getDate());
a=a.replace(/HH/,padLeft(this.getHours(),2,"0"));a=a.replace(/H/,this.getHours());a=a.replace(/mm/,padLeft(this.getMinutes(),2,"0"));a=a.replace(/m/,this.getMinutes());
a=a.replace(/ss/,padLeft(this.getSeconds(),2,"0"));a=a.replace(/s/,this.getSeconds());a=a.replace(/SSS/,padLeft(this.getMilliseconds(),3,"0"));a=a.replace(/S/,this.getMilliseconds());
return a;};if(Date._parse==null){Date._parse=Date.parse;Date.parse=function(a,c){if(isNullOrBlank(a)){return null;}c=c===true;if(c){a=a.replace(/-/g,"/");
return Date._parse(a);}else{a=a.replace(/年/g,"-");a=a.replace(/月/g,"-");a=a.replace(/日/g,"");a=a.replace(/时/g,":");a=a.replace(/点/g,":");a=a.replace(/分/g,":");
a=a.replace(/秒/g,"");a=a.replace(/毫秒/g,"");a=a.replace(/\s{2,}/g," ");a=a.replace(/-/g,"/");var d=a.indexOf(".");if(d!=-1){var b=parseInt(a.substring(d+1));
a=a.substring(0,d);if(isNum(b)&&b>0){return Date._parse(a)+b;}else{return Date._parse(a);}}else{return Date._parse(a);}}};Date.parseAsDate=function(a){if(isDate(a)){return a;
}else{if(isNum(a)){return new Date(a);}else{return new Date(Date.parse(a));}}};Date.isValidDate=function(a){return !isNaN(Date.parse(a,true));};}Date.prototype.isLeapYear=function(){return isLeapYear(this.getFullYear());
};Date.prototype.getMonthDays=function(){return getYearMonthDays(this.getFullYear(),this.getMonth()+1);};if(Date.prototype._toString==null){Date.prototype._toString=Date.prototype.toString;
Date.prototype.toString=function(a){if(typeof a=="undefined"){return this._toString();}else{return this.format(a);}};}Date.prototype.diff=function(b,a){if(a==null){a="milliSecond";
}var c=this-b;switch(a.toLowerCase()){case"year":return this.getFullYear()-b.getFullYear();case"month":return(this.getFullYear()-b.getFullYear())*12+(this.getMonth()-b.getMonth());
case"day":return Math.floor(c/86400000);case"hour":return Math.floor(c/3600000);case"minute":return Math.floor(c/60000);case"second":return Math.floor(c/1000);
case"week":return Math.floor(c/604800000);case"quarter":return Math.ceil(this.diff(b,"month")/3);case"millisecond":return c;default:return null;}};Date.prototype.getWeek=function(){var f=new Date(this.getFullYear(),0,1);
var b=f.getDay();var e=new Date(this.getFullYear(),this.getMonth(),this.getDate());var d=e.diff(f,"day");var c=Math.floor(d/7);var a=d-c*7;return 1+c+Math.floor((b+a)/7);
};Date.prototype.asJSON=function(){var a={};a.year=this.getFullYear();a.month=this.getMonth()+1;a.day=this.getDate();a.hour=this.getHours();a.minute=this.getMinutes();
a.second=this.getSeconds();a.milliSecond=this.getMilliseconds();a.dayOfWeek=this.getDay();a.weekOfYear=this.getWeek();a.quarter=Math.ceil((this.getMonth()+1)/3);
return a;};Date.prototype.beginTime=function(){return new Date(this.getFullYear(),this.getMonth(),this.getDate(),0,0,0,0);};Date.prototype.endTime=function(){var a=this.addDays(1).beginTime();
return new Date(a.getTime()-1);};Date.prototype.add=function(c,a){if(a==null){a="milliSecond";}switch(a.toLowerCase()){case"year":var d=this.asJSON();d.year+=c;
return new Date(d.year,d.month-1,d.day,d.hour,d.minute,d.second,d.milliSecond);case"month":var d=this.asJSON();var b=Math.floor(c/12);var e=c%12;d.year+=b;
d.month+=e;return new Date(d.year,d.month-1,d.day,d.hour,d.minute,d.second,d.milliSecond);case"day":return new Date(this.getTime()+86400000*c);case"hour":return new Date(this.getTime()+3600000*c);
case"minute":return new Date(this.getTime()+60000*c);case"second":return new Date(this.getTime()+1000*c);case"week":return new Date(this.getTime()+604800000*c);
case"quarter":return this.add(c*3,"month");case"millisecond":return new Date(this.getTime()+c);default:return null;}};Date.prototype.addYears=function(a){return this.add(a,"year");
};Date.prototype.addMonths=function(a){return this.add(a,"month");};Date.prototype.addDays=function(a){return this.add(a,"day");};Date.prototype.addHours=function(a){return this.add(a,"hour");
};Date.prototype.addMinutes=function(a){return this.add(a,"minute");};Date.prototype.addSeconds=function(a){return this.add(a,"second");};Date.prototype.addWeeks=function(a){return this.add(a,"week");
};Date.prototype.addQuarters=function(a){return this.add(a,"quarter");};Date.prototype.getPart=function(a){if(a==null){a="milliSecond";}switch(a.toLowerCase()){case"year":return this.getFullYear();
case"month":return this.getMonth()+1;case"day":return this.getDate();case"hour":return this.getHours();case"minute":return this.getMinutes();case"second":return this.getSeconds();
case"millisecond":return this.getMilliseconds();case"dayofweek":return this.getDay();case"weekofyear":return this.getWeek();case"quarter":return Math.ceil((this.getMonth()+1)/3);
default:return null;}};function getObjAttr(_objToEval,attrName){var tmpAttrName=escapeJsonStr(attrName);var evalStr='( _objToEval["'+trim(tmpAttrName)+'"] )';
return eval(evalStr);}var __isJSONDefined=typeof(JSON)!=="undefined"&&(isFunction(JSON.parse)||isFunction(JSON.stringify));function isJSONDefined(){__isJSONDefined=false;
return __isJSONDefined;}if(!isJSONDefined()){JSON={};}function objFromJsonStr(jsonStr){try{return eval("("+jsonStr+")");}catch(exp){throw new TypeError("JSON parse error !");
}}if(!isJSONDefined()){JSON.parse=objFromJsonStr;}if(isFunction(JSON.parse)){JSON.decode=JSON.parse;JSON.decodeStr=function(a){return a==null?null:decodeURIComponent(a);
};}function objToJsonStr(d){var c='"';var j=arguments.callee;if(d==null||isNumber(d)||isBoolean(d)){return d;}else{if(isString(d)){return c+escapeJsonStr(d)+c;
}else{if(isDate(d)){return c+d.format("yyyy-MM-dd HH:mm:ss")+c;}else{if(isArray(d)){var f=d.length;var k=new Array();for(var e=0;e<f;e++){k[e]=j(d[e]);
}return"["+k.join(",")+"]";}else{if(typeof(d.toJSON)=="function"){return d.toJSON();}else{var a=new Array();var g=0;var b=Object.hasOwnProperty;for(var h in d){if(b.call(d,h)){var l=d[h];
a[g++]=j(h)+":"+j(l);}}return"{"+a.join(",")+"}";}}}}}}if(!isJSONDefined()){JSON.stringify=objToJsonStr;}if(isFunction(JSON.stringify)){JSON.encode=JSON.stringify;
JSON.encodeStr=function(a){return a==null?null:encodeURIComponent(a);};}function KeyMap(b){this.name="";if(b!=null){this.name=""+b;}var a={};this.clear=function(){a={};
return this;};this.from=function(c){if(c==null){c={};}a=c;return this;};this.set=function(c,d){a[c]=d;return this;};this.get=function(c){return a[c];};
this.contains=function(c){return typeof a[c]!="undefined";};this.add=function(c,d){if(!this.contains(c)){a[c]=d;return true;}return false;};this.remove=function(c){if(this.contains(c)){var d=a[c];
delete a[c];return d;}return undefined;};this.keys=function(){var e=[];var d=e.length;for(var c in a){e[d++]=c;}return e;};this.size=function(){var c=0;
for(xKey in a){c++;}return c;};this.clone=function(e){var c=new KeyMap(e);var g=this.keys();var d=g.length;for(var f=0;f<d;f++){var h=g[f];c.set(h,this.get(h));
}return c;};this.reverse=function(){var g={};var f=this.keys();for(var e=0,c=f.length-1;c>=0;e++,c--){var d=f[c];g[d]=a[d];}a=g;return this;};this.toObject=function(){return merge({},a);
};this.toJSON=function(){var f=this.keys();var j=f.length;var g=new Array();var c=0;for(var e=0;e<j;e++){var h=f[e];var d=this.get(h);g[c++]=JSON.stringify(h+"")+":"+JSON.stringify(d);
}return"{"+g.join(",")+"}";};this.toString=this.toJSON;}KeyMap.from=function(a){var b=new KeyMap();b.from(a);return b;};function merge(d,a){d=d||{};a=a||{};
var f=KeyMap.from(a);var e=f.keys();for(var c=0;c<e.length;c++){var b=e[c];d[b]=f.get(b);}return d;}function syncDataBy(d,c){if(d==null||typeof c!="function"){return;
}var e=Object.hasOwnProperty;for(var b in d){if(e.call(d,b)){try{c(b,d[b],d);}catch(a){}}}}function compareArrays(q,p,g,l){var r={more:[],less:[],same:[],different:[]};
if(p==null){p=[];}if(q==null){q=[];}var o=p.length;var n=q.length;if(o==0){r.more=q;}else{if(n==0){r.less=p;}else{if(typeof(g)!="function"){g=function(j,s){return j==s;
};}q=copyArray(q);p=copyArray(p);var f=r.more;var k=r.less;var h=r.same;var b=r.different;for(var d=o-1,c=n-1;d>=0||c>=0;){var a=d>=0?p[d]:undefined;var e=c>=0?q[c]:undefined;
if(d>=0){var m=q.indexOf(a,null,l);if(m!=-1){e=q[m];if(g(e,a)){h[h.length]=e;}else{b[b.length]=e;}q.removeAt(m);p.removeAt(d);d--;c--;}else{k[k.length]=a;
p.removeAt(d);d--;}}else{f[f.length]=e;q.removeAt(c);c--;}}}}r.more=r.more.reverse();r.less=r.less.reverse();r.same=r.same.reverse();r.different=r.different.reverse();
return r;}function compareRecordsById(g,b,f,e){var h=null;if(typeof(f)=="function"){h=f;}else{var c=f;if(typeof(c)=="string"){if((c=c.trim())==""){c="id";
}}else{c="id";}h=function(k,j){if(k==j){return true;}else{if(k!=null&&j!=null){return k[c]==j[c];}else{return false;}}};}if(typeof(e)!="function"){e=function(k,j){if(k==j){return true;
}else{if(k!=null&&j!=null){for(var l in k){if(k[l]!=j[l]){return false;}}for(var l in j){if(k[l]!=j[l]){return false;}}return true;}else{return false;}}};
}var d=compareArrays(g,b,e,h);delete d.same;var a={added:d.more,deleted:d.less,modified:d.different};return a;}function getClassOf(a){if(a==null){return null;
}if(isFunction(a)){return Function;}else{return a.constructor;}}function getFuncName(e){if(!isFunction(e)){return null;}var d=/^function(\s)+([\w\$]+?(\s)*\()/i;
var a=e.toString().trim();var b=a.match(d);if(b!=null&&b.length>0){var c=b[0].trim();var f=c.substring(8,c.length-1);f=f.trim();return f;}return null;}function getClassNameOf(b){var a=getClassOf(b);
return a==null?null:getFuncName(a);}function createFrom(obj,argx){if(obj==null){return undefined;}var objClass=null;if(!isFunction(obj)){objClass=getClassOf(obj);
}else{objClass=obj;}var args=arguments;var argCount=args.length;if(argCount>1){var paramStrs=new Array();for(var i=0;i<argCount-1;i++){paramStrs[i]="args["+(i+1)+"]";
}var evalStr="new objClass("+paramStrs.join(", ")+")";return eval(evalStr);}else{return new objClass();}}function isMoneyStr(c,d){if(c==null){return false;
}c=""+c;d=d==true;var b=d?/^(\+|-)?([0-9]|[1-9][0-9]*)(\.\d+)?$/ig:/^([0-9]|[1-9][0-9]*)(\.\d+)?$/ig;var a=c.match(b);return a!=null&&a.length==1;}function isNatualStr(c){if(c==null){return false;
}c=""+c;var b=/^([0-9]|[1-9][0-9]*)$/ig;var a=c.match(b);return a!=null&&a.length==1;}function isValidEmail(b){var a=/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;
return a.test(b);}function isDigitStr(b){var a=/^(\d)+$/;return a.test(b);}function isDigitOrHyphenStr(b){var a=/^(\d|-)+$/;return a.test(b);}function isMobile(b){if(b==null||b.length!=11){return false;
}var a=/^1[3|4|5|7|8]\d{9}$/;return a.test(b);}function isTelNo(b){if(b==null||b.length<7){return false;}var a=/(^([0][1-9][0-9]-?)?[0-9]{8}$)|(^([0][1-9]{3}-?)?[0-9]{7}$)/;
return a.test(b);}function isPhoneNumber(a){return isMobile(a)||isTelNo(a);}function getById(a){return document.getElementById(a);}function getServerBase(a){if(typeof a=="undefined"){a=window.document.URL;
}var b=a.indexOf("://")+3;b=a.indexOf("/",b);return a.substring(0,b);}function setPageTitle(a){document.title=a;}function setPageUrl(a){window.location.href=a;
}function RepeatClickChecker(){var b=1000;var a={};this.isValidFor=function(d,c){var f=a[d];var e=new Date().getTime();a[d]=e;if(f==null){return true;}else{if(typeof c=="undefined"){c=b;
}return e-f>=c;}};}var repeatClickChecker=new RepeatClickChecker();var __cachedHostWin;function getHostWindow(){if(typeof __cachedHostWin=="undefined"){var a=window.parent;
if(a!=null&&a!=window){__cachedHostWin=a.window;}else{__cachedHostWin=null;}}return __cachedHostWin;}function hasHostWindow(){return getHostWindow()!==null;
}function getFrameWindow(){if(hasHostWindow()){return window.frameElement;}else{return null;}}function callHostFunc(e){var c=getHostWindow();if(c!=null){var a=e;
if(typeof e=="string"){a=c[e];}if(typeof a=="function"){var d=arguments.length;var b=d>1?Array.prototype.slice.call(arguments,1):[];a.apply(c,b);}}}function __echoWindowInfo(){var b=window.document.title;
var a=window.location.href;alert("["+b+"]\n"+a);}function echoHostWindow(){callHostFunc(__echoWindowInfo);}var __pageName=null;function setPageName(a){__pageName=a;
}function getPageName(){return __pageName||document.title;}function notifyHostPageLoad(a){if(hasHostWindow()){var b=getHostWindow();var c=b.dialogMonitor;
c.notifyPageLoad(getPageName(),a);}}function getThisPageArgs(){if(hasHostWindow()){var a=getHostWindow();var b=a.dialogMonitor;return b.getPageArgs(getPageName());
}return null;}function notifyHostPageResult(a){if(hasHostWindow()){var b=getHostWindow();var c=b.dialogMonitor;c.notifyPageResult(getPageName(),a);}}function getThisPageDialog(){if(hasHostWindow()){var a=getHostWindow();
var b=a.dialogMonitor;return b.getPageDialog(getPageName());}return null;}var dialogMonitor={pageDialogs:{},setPageDialog:function(a,b){this.pageDialogs[a]=b;
},getPageDialog:function(a){return this.pageDialogs[a];},pageArguments:{},setPageArgs:function(a,b){this.pageArguments[a]=b;},getPageArgs:function(a){return this.pageArguments[a];
},pageEventHandlers:{},addPageHandler:function(a,b){this.pageEventHandlers[a]=b;},removePageHandler:function(a){delete this.pageEventHandlers[a];},notifyPageLoad:function(b,a){var c=this.pageEventHandlers[b];
if(c!=null){var d=c.onPageLoad;if(typeof d=="function"){d(b,a);}}},notifyPageResult:function(b,a){var d=this.pageEventHandlers[b];if(d!=null){var c=d.onPageResult;
if(typeof c=="function"){c(a);}}}};function changePageUrl(a){window.location.href=a;}function downloadFromUrl(a,c){var d="_unique_dowload_url_link";var b=document.getElementById(d);
if(b==null){b=document.createElement("A");b=document.body.appendChild(b);b.id=d;b.style.display="none";b.target="_self";b.onclick="return false;";}if(c){b.target=c;
}b.href=a;b.click();}function parseUrl(d){if(typeof d=="undefined"){d=window.document.URL;}var h={};var m=d.indexOf("://");h.scheme=d.substring(0,m);var f=m+3;
var e=d.indexOf("/",f);var a=d.substring(f,e);var q=a.indexOf(":");h.host=q!=-1?a.substring(0,q):a;h.port=q!=-1?parseInt(a.substring(q+1)):80;var p=d.substring(e);
var g=p.indexOf("#");if(g!=-1){h.frags={};var l=p.substring(g).replace(/^[^#]*#?(.*)$/,"$1").trim();if(l!=""){var b=l.split("&");for(var o=0,n=b.length;
o<n;o++){var k=b[o].split("=");h.frags[k[0]]=k[1];}}p=p.substring(0,g);}var r=p.indexOf("?");h.uri=r==-1?p:p.substring(0,r);var t=r==-1?-1:r+1;h.params={};
if(t!=-1){var c=p.substring(t).trim();var s=c.length>0?c.split("&"):[];for(var o=0,n=s.length;o<n;o++){var k=s[o].split("=");h.params[k[0]]=k[1];}}return h;
}function extractUrlParams(a){return parseUrl(a).params;}function concatUrlParams(k,d,n){if(d==null){return k;}var l=null;var c=k.indexOf("#");if(c!=-1){l=k.substring(c).replace(/^[^#]*#?(.*)$/,"$1").trim();
l=l==""?null:l;k=k.substring(0,c);}n=n===true;var h="";if(typeof d=="string"){h=d;}else{var a=Object.hasOwnProperty;var o=new Array();var g=0;for(var j in d){if(a.call(d,j)){var m=d[j];
if(typeof m=="function"){m=m();}if(m==null){continue;}if(isArray(m)){var f=m.length;for(var e=0;e<f;e++){if(n){o[g++]=encodeURIComponent(j)+"="+encodeURIComponent(m[e]);
}else{o[g++]=j+"="+m[e];}}}else{if(isDate(m)){m=m.format("yyyy-MM-dd HH:mm:ss");}else{if(isPlainObject(m)){m=JSON.encode(m);}}if(n){o[g++]=encodeURIComponent(j)+"="+encodeURIComponent(m);
}else{o[g++]=j+"="+m;}}}}h=o.join("&");}var b="";if(k==null){k="";}else{if(k.indexOf("?")==-1){b="?";}else{if(!k.endsWith("?")){b="&";}}}return k+b+h+(l==null?"":"#"+l);
}function makeUrl(){return concatUrlParams.apply(window,arguments);}function jsonToUrlParams(b,a){return concatUrlParams(null,b,a);}var __uniqueRequestName="__Unique_Request_Id";
function genUniqueStr(){var a=new Number(new Date());var b=Math.round(Math.random()*10000)+"_"+Math.round(Math.random()*10000);return a+"_"+b;}function makeUniqueRequest(a){return concatUrlParams(a,__uniqueRequestName+"="+genUniqueStr());
}var __screenWidth=window.screen.availWidth;var __screenHeight=window.screen.availHeight;function __showDlgBase(e,j,a,k,f){var c=k?window.showModalDialog:window.showModelessDialog;
if(!c){alert("您的浏览器不支持"+(k?"模态对话框[showModalDialog]":"非模态对话框[showModelessDialog]")+"，请使用支持 模态对话框 的浏览器！");return null;}if(typeof(j)=="undefined"||j==null){j=window;
}var h={};if(typeof(a)=="undefined"||a==null){a={};}var b=null;if((b=a.width)!=null){b=parseInt(b);b=!isNum(b)||b<=0?600:b;if(b>__screenWidth){b=__screenWidth;
}h.width=b;}else{h.width=800;}if((b=a.height)!=null){b=parseInt(b);b=!isNum(b)||b<=0?400:b;if(b>__screenHeight){b=__screenHeight;}h.height=b;}else{h.height=600;
}if((b=a.center)!=null){h.center=b!=false;}else{h.center=true;}if((b=a.scrollbars)!=null){h.scrollbars=b!=true;}else{h.scrollbars=false;}if((b=a.status)!=null){h.status=b!=true;
}else{h.status=false;}if((b=a.resizable)!=null){h.resizable=b!=false;}else{h.resizable=true;}if((b=a.maximized)!=null){h.maximized=b!=true;}else{h.maximized=false;
}if(h.maximized==true){h.left=0;h.top=0;h.width=__screenWidth;h.height=__screenHeight;}else{if(h.center==true){var d=(__screenWidth-h.width)/2;h.left=d;
var g=(__screenHeight-h.height)/2;if(g<0){g=0;}h.top=g;}}h.help=false;var l="";l+="help:"+(h.help?"yes":"no")+";";l+="dialogLeft:"+h.left+"px;";l+="dialogTop:"+h.top+"px;";
l+="dialogWidth:"+h.width+"px;";l+="dialogHeight:"+h.height+"px;";l+="center:"+(h.center?"yes":"no")+";";l+="status:"+(h.status?"yes":"no")+";";l+="scrollbars:"+(h.scrollbars?"yes":"no")+";";
l+="resizable:"+(h.resizable?"yes":"no");f=!(f==false);if(f){e=makeUniqueRequest(e);}return c(e,j,l);}function showModalDlg(d,c,b,a,e){if(typeof a=="boolean"){e=a;
a=null;}if(a==null&&typeof doBeforeDlgOpen=="function"){a=doBeforeDlgOpen;}if(a!=null&&typeof a=="function"){a.call(window);}return __showDlgBase(d,c,b,true,e);
}function showModelessDlg(e,d,b,a,f){if(typeof a=="boolean"){f=a;a=null;}if(a==null&&typeof doBeforeDlgOpen=="function"){a=doBeforeDlgOpen;}if(a!=null&&typeof a=="function"){try{a.call(window);
}catch(c){}}return __showDlgBase(e,d,b,false,f);}if(typeof window.dialogArguments!="undefined"&&typeof doAfterDlgOpen=="function"){try{doAfterDlgOpen.call(window);
}catch(ex){}}function openWindow(c,b){var a="";if(typeof(b)=="undefined"){var b=new Object();}if(typeof(b.name)=="undefined"){b.name="win"+Math.round(Math.random()*100000);
}if(typeof(b.height)!="undefined"&&typeof(b.fullscreen)=="undefined"){a+="height="+b.height+",";}if(typeof(b.width)!="undefined"&&typeof(b.fullscreen)=="undefined"){a+="width="+b.width+",";
}if(typeof(b.fullscreen)!="undefined"){a+="width="+screen.availWidth+",";a+="height="+screen.availHeight+",";}if(typeof(b.center)=="undefined"){b.x=0;b.y=0;
a+="screenx="+b.x+",";a+="screeny="+b.y+",";a+="left="+b.x+",";a+="top="+b.y+",";}if(typeof(b.center)!="undefined"&&typeof(b.fullscreen)=="undefined"){b.y=Math.floor((screen.availHeight-(b.height||screen.height))/2)-(screen.height-screen.availHeight);
b.x=Math.floor((screen.availWidth-(b.width||screen.width))/2)-(screen.width-screen.availWidth);a+="screenx="+b.x+",";a+="screeny="+b.y+",";a+="left="+b.x+",";
a+="top="+b.y+",";}if(typeof(b.scrollbars)!="undefined"){a+="scrollbars=1,";}if(typeof(b.menubar)!="undefined"){a+="menubar=1,";}if(typeof(b.locationbar)!="undefined"){a+="location=1,";
}if(typeof(b.resizable)!="undefined"){a+="resizable=1,";}return window.open(c,b.name,a);}function closePageWindow(){window.opener=null;window.open("","_self");
window.close();}function isEditable(a){if(isString(a)){a=document.getElementById(a);}return a!=null&&!a.readOnly&&!a.disabled;}function addStyleClass(d,c){if(isString(d)){d=document.getElementById(d);
}if(d==null){return;}if(c==null||c.isBlank()){return;}var b=d.className;if(b==null){b="";}var a=replaceRegStr(b,"(\\s)+",",");var e=a.split(",");if(e.indexOf(c)==-1){e.append(c);
}d.className=e.join(" ").trim();}function removeStyleClass(d,c){if(isString(d)){d=document.getElementById(d);}if(d==null){return;}if(c==null||c.isBlank()){return;
}var b=d.className;if(b==null){b="";}var a=replaceRegStr(b,"(\\s)+",",");var e=a.split(",");if(e.indexOf(c)!=-1){e.remove(c);}d.className=e.join(" ").trim();
}function replaceStyleClass(f,c,b,d){if(isString(f)){f=document.getElementById(f);}if(f==null){return;}var e=f.className;if(e==null){e="";}var a=replaceRegStr(e,"(\\s)+",",");
var g=a.split(",");var h=g.indexOf(c);if(h==-1){if(d==true&&b!=null&&!b.isBlank()){g.append(b);}}else{if(b==null||b.isBlank()){g.remove(c);}else{g[h]=b;
}}f.className=g.join(" ").trim();}function shiftSelItems(e,h){var b=e;if(typeof(e)=="string"){b=document.getElementById(e);}var a=h;if(typeof(h)=="string"){a=document.getElementById(h);
}var c=b.options;var g=a.options;for(var f=c.length-1;f>=0;f--){var d=c[f];if(d.selected){g[g.length]=new Option(d.text,d.value);d.parentNode.removeChild(d);
}}}function getFormElementsByName(k,a){var f=null;if(k==null){return null;}else{f=k;if(typeof(k)=="string"){f=document.getElementById(k);}if(f.tagName!="FORM"){return null;
}}var g=[];var b=copyArray(f.elements);var h=b.length;for(var e=0,d=0;e<h;e++){var c=b[e];if(c!=null&&c.name==a){g[d++]=c;}}return g;}function getRadioGroupValue(f,b){if(b==null){b=document;
}if(f!=null&&f.name!=null){f=f.name;}var e=[];if(b.getElementsByName){e=b.getElementsByName(f);}else{if(b.tagName=="FORM"){e=getFormElementsByName(b,f);
}else{e=document.getElementsByName(f);}}var a=e.length;if(a<=0){return null;}for(var c=0;c<a;c++){var d=e[c];if(d.checked){return d.value;}}return null;
}function setRadioGroupValue(g,e,b){if(b==null){b=document;}if(g!=null&&g.name!=null){g=g.name;}var f=[];if(b.getElementsByName){f=b.getElementsByName(g);
}else{if(b.tagName=="FORM"){f=getFormElementsByName(b,g);}else{f=document.getElementsByName(g);}}var a=f.length;if(a<=0){return;}for(var c=0;c<a;c++){var d=f[c];
d.checked=e==d.value;}}function getCheckGroupValue(h,b){if(b==null){b=document;}if(h!=null&&h.name!=null){h=h.name;}var d=[];if(b.getElementsByName){d=b.getElementsByName(h);
}else{if(b.tagName=="FORM"){d=getFormElementsByName(b,h);}else{d=document.getElementsByName(h);}}var a=d.length;if(a<=0){return null;}var g=[];for(var e=0,c=0;
e<a;e++){var f=d[e];if(f.checked){g[c++]=f.value;}}return g.length>0?g:null;}function setCheckGroupValue(g,f,b){if(b==null){b=document;}if(g!=null&&g.name!=null){g=g.name;
}var c=[];if(b.getElementsByName){c=b.getElementsByName(g);}else{if(b.tagName=="FORM"){c=getFormElementsByName(b,g);}else{c=document.getElementsByName(g);
}}var a=c.length;if(a<=0){return;}if(!isArray(f)){f=[];}for(var d=0;d<a;d++){var e=c[d];e.checked=f.indexOf(e.value)!=-1;}}function getSelectValue(a){var h=a;
if(typeof(a)=="string"){h=document.getElementById(a);}var f=h.options;var g=f.length;if(h.multiple){var d=[];for(var c=0,b=0;c<g;c++){var e=f[c];if(e.selected){d[b++]=e.value;
}}return d.length>0?d:null;}else{for(var c=0;c<g;c++){var e=f[c];if(e.selected){return e.value;}}return null;}}function getSelectText(a){var h=a;if(typeof(a)=="string"){h=document.getElementById(a);
}var f=h.options;var g=f.length;if(h.multiple){var d=[];for(var c=0,b=0;c<g;c++){var e=f[c];if(e.selected){d[b++]=e.text;}}return d.length>0?d:null;}else{for(var c=0;
c<g;c++){var e=f[c];if(e.selected){return e.text;}}return null;}}function setSelectValue(a,f){var g=a;if(typeof(a)=="string"){g=document.getElementById(a);
}var d=g.options;var e=d.length;g.selectedIndex=-1;if(g.multiple){if(!isArray(f)){f=[];}for(var b=0;b<e;b++){var c=d[b];c.selected=f.indexOf(c.value)!=-1;
}}else{if(f==null){return;}for(var b=0;b<e;b++){var c=d[b];if(c.value==f){g.selectedIndex=b;return;}}}}function clearSelectData(a){var f=a;if(typeof(a)=="string"){f=document.getElementById(a);
}var d=f.options;var e=d.length;for(var b=e-1;b>=0;b--){var c=d[b];c.parentNode.removeChild(c);}}function loadSelectData(l,q,f,p){if(typeof(f)=="undefined"||f==null){f={valueField:"value",textField:"text",unSelectedVal:""};
}if(typeof(p)=="undefined"){p=f.unSelectedVal;}var g=l;if(typeof(l)=="string"){g=document.getElementById(l);}clearSelectData(g);var o=q==null?0:q.length;
var r=f.valueField==null?"value":f.valueField;var j=f.textField==null?"text":f.textField;var e=f.unSelectedVal==null?"":f.unSelectedVal;var c=-1;var k=-1;
var a=g.options;for(var n=0;n<o;n++){var h=q[n];var m=h[j];var d=h[r];var b=new Option(m,d);b.title=m;a[n]=b;if(p==d){c=n;}else{if(c==-1&&e==d){k=n;}}}if(c==-1&&k!=-1){c=k;
}g.selectedIndex=c;return c;}function escapeHtmlStr(a){if(a==null){return null;}var b=""+a;b=replaceStr(b," ","&nbsp;");b=replaceStr(b,"<","&lt;");b=replaceStr(b,">","&gt;");
b=replaceStr(b,"\n","<br>");return b;}function asFixedThinTable(a){var b=a;if(b==null){return;}if(typeof b=="string"){b=document.getElementById(b);}if(b==null||b.tagName!="TABLE"){return;
}b.border="0";b.cellPadding="0";b.cellSpacing="1";b.style.tableLayout="fixed";b.style.borderCollapse="separate";}function indexInMergedArray(e,d){var b=d.length;
var a=0;for(var c=0;c<b;c++){a+=d[c];if(a-1>=e){return c;}}return -1;}function indexOfColInTableRow(f,e){if(typeof(f)!="number"){f=ParseInt(f);}if(!isNum(f)){return -1;
}if(e==null||e.tagName==null||e.tagName.toUpperCase()!="TR"){return -1;}var b=e.cells;var d=[];for(var c=0;c<b.length;c++){var a=b[c];var g=1;if(a.colSpan!=null){g=ParseInt(a.colSpan);
if(!isNum(g)||g<1){g=1;}}d[c]=g;}return indexInMergedArray(f,d);}function calcTrackerDim(f){var d,g,h,c;var a=$("#"+f.refId);var e=a.offset().left;var j=a.offset().top;
var b=a.width();var k=a.height();g=k/f.refHeight*f.top+j;d=b/f.refWidth*f.left+e;h=b/f.refWidth*(f.left+f.width)+e-d;c=k/f.refHeight*(f.top+f.height)+j-g;
return{left:Math.round(d),top:Math.round(g),width:Math.round(h),height:Math.round(c)};}